### ISSUE TITLE
Future of Context

### ISSUE THREAD

**Issue by nbasargin** [Roboy/DialogSystem#34]
Context is used to store non-permanent or changing information like dialog intents or face coordinates. The current implementation is a singleton and was not designed to support multiple conversations (in a sequence or at the same time). This leads to some problems like:
 - states can not assume that context data comes from the current conversation
 - with concurrent conversations, one conversation can read and change data of another one
 - Context can be accesses from anywhere, even from code that shouldn't be allowed to touch it

We have to come up with a solution for those problems in order to support multiple conversations. A use case for multiple conversations is a chat bot for Telegram.

One of possible solutions would be to create a new Context for every conversation.

**Comment by l-laura** [comment]
It seems that there are two very different usage scenarios for the Context:

1) When Roboy interacts with physical users and the full Cognition infrastructure is set up, there's information about the environment that is not limited to a single conversation. This was the basis for many design decision for the current Context (singleton, globally available) and reflects in the sample implementations for Vision and triggers.
2) The structure of (1) works fine for a single conversation. To support multiple conversations, our main concern is to offer separation of information. We want to store and access the interlocutor, conversation topics etc. individually. The implementations of Values and Histories are reusable for that, but we'd need a class that can be initiated at the beginning of each new conversation.

There are Values and Histories that are pretty obviously conversation-specific. I'd start by moving them out of the main Context into a separate class with its own constructor. I don't know how these instances would be handled during runtime - is there a separate manager for multiple state machines, one for each conversation?

**Comment by nbasargin** [comment]
Resolved in #43: there is a separate Context object for every Conversation
