### ISSUE TITLE
Questions are not parsed correctly

### ISSUE THREAD

**Issue by ninalovegood** [Roboy/DialogSystem#36]
Example: "Could you play a game", semantic parser returns failure, object answer is the whole sentence

Expected: parser_result="SUCCESS", sem_triple=(subject:Roboy, predicate:ability, object:game), OBJ_ANSWER="game"

The user should be able to ask roboy if he can play a game, then he suggests possible games.

**Comment by emlozin** [comment]
This is not dialog system related. This is the issue for the parser. And this is not a bug but some functionality that one needs to add to grammar.

**Comment by Waguramu** [comment]
@emlozin I asked to put it here, it is also dialog related as not only semantic parser cannot process it

**Comment by emlozin** [comment]
@Waguramu then imho it would be better to reformulate, 'cause now it seems strictly parser related :P

**Comment by nbasargin** [comment]
@ninalovegood @emlozin @Waguramu is there still an issue with the parser?

**Comment by Waguramu** [comment]
Indeed, there is, my sweet summer child.
@nbasargin
