### ISSUE TITLE
AnswerAnalyzer returns capitalized tokens instead of lowercase tokens.

### ISSUE THREAD

**Issue by Mireu** [Roboy/DialogSystem#38]
roboy.linguistics.sentenceanalysis.AnswerAnalyzer.analyze(sentence) returns capitalized attributes inside the interpretation.

**Observed** in: AnswerAnalyzerTest

**Description**: AnswerAnalyzerTest analyzes sentences through ->SimpleTokenizer->OpenNLPPPOSTagger->OpenNLPParser->AnswerAnalyzer and checks if specific attributes are equal to the expected outcomes of the analyze-operation. These are provided in capitalized form ('Robot') but should be provided in lowercase form ('robot').

**Comment by Waguramu** [comment]
It is a bug which is also a feature in one of the Tokenizers, since now we have two 
Fixable

**Comment by Waguramu** [comment]
Solved. The fix available in the next PR
