### ISSUE TITLE
Update readme

### ISSUE THREAD

**Issue by nbasargin** [Roboy/DialogSystem#59]
## Requirements for the readme on GitHub:
- should explain all steps to get the system running
- even an inexperienced student (2nd/3rd semester) should be able to understand and follow it
- should not contain architecture description (this goes to readthedocs)
- should contain a link to readthedocs

## Following should be in the roboy_dialog readme:
- [x] Link to readthedocs 
- [x] How much HDD space is required to install the complete system + dependencies?
- [x] What dependencies are optional (like ROS) and when do we really need them?
- [x] List of all commands I have to type into the terminal to get the dependencies (``sudo apt install XXX``)
- [x] List of steps needed to install Neo4J locally (or a link to another readme/readthedocs)
  - [x] What type of installation is preferred (docker/native)?
  - [x] How to install using docker?
  - [x] How to get the docker container that contains an empty database?
  - [x] How to get the docker container that contains a pre-filled database?
  - [x] How to set all relevant environment variables?
- [x] What options are important and should be set in the config file?
- [ ] What to expect when the system is running (long parser loading? tons of weird logging output? ...)
- [x] What OS is recommended (Ubuntu 16)?
- [x] How to run the dialog ...
  - [x] ... from command line
  - [x] ... from the IDE
- [x] What dependencies must be installed (like maven, ruby etc.)?
- [x] In which directory should the user type ``mvn clean install`` 
       (surprise, "in the directory containing pom.xml" won't do, we have many poms)
- [x] How to correctly clone the roboy_dialog repo 
      (surprise, just ``git clone`` won't do because of submodules)
- [x] What IDE is recommended (IntelliJ)?
- [x] How much RAM is needed to run the system?

**Comment by Aevyz** [comment]
All these things I have ticked can be found @ https://roboy-dialog-doc-test.readthedocs.io/en/latest/Usage/0_installation.html

**Comment by Aevyz** [comment]
d967bd162c393231fe654341f22b892aa3f71234

- Regarding disk space, I have no idea how much space it is going to take, would a ball park estimate do? (so +/- a few gigabytes)
- Pre-filled DB coming soon tm
- I'll add a page regarding expectable output to the Readme tomorrow
- Regarding Config File stuff, I think a page in the docs makes more sense, can either @josephbirkner @Mireu or @Waguramu do that please? 

Also there is now a absolute beginners guide to installing and a TOC

**Comment by Aevyz** [comment]
Solved by https://github.com/Roboy/roboy_dialog/pull/62
