### ISSUE TITLE
Telegram sticker is not processed as input for the telegram bot

### ISSUE THREAD

**Issue by missxa** [Roboy/DialogSystem#82]
When only a sticker is sent to the bot, dialog's IO `listen()` method does not receive it and therefore dialog cannot react

**Comment by polynominom** [comment]
https://github.com/Roboy/roboy_dialog/blob/60fb47da888a0adcbe1ba2e4f2e32ad0fde955db/dialog/src/main/java/roboy/util/TelegramCommunicationHandler.java#L105
